In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re, csv

In [24]:
df = pd.read_csv("Chess Database Processed.csv")

In [25]:
df.head()

Board State  Eval
0  rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR ...  0.12
1  rnbqkb1r/pppppppp/5n2/8/3P4/8/PPP1PPPP/RNBQKBN...  0.20
2  rnbqkb1r/pppppppp/5n2/6B1/3P4/8/PPP1PPPP/RN1QK...  0.10
3  rnbqkb1r/pppppp1p/5np1/6B1/3P4/8/PPP1PPPP/RN1Q...  0.44
4  rnbqkb1r/pppppp1p/5Bp1/8/3P4/8/PPP1PPPP/RN1QKB...  0.12

In [26]:
Outcome = df.values[:,1]
input1 = df.values[:,0]
input1

array(['rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq d3 0 1',
       'rnbqkb1r/pppppppp/5n2/8/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 1 2',
       'rnbqkb1r/pppppppp/5n2/6B1/3P4/8/PPP1PPPP/RN1QKBNR b KQkq - 2 2',
       ..., '5rk1/Prp2ppp/2Qp1q2/1P2p3/R3Pn2/5N1P/5PPK/3R1B2 b - - 2 29',
       '5rk1/Prp1qppp/2Qp4/1P2p3/R3Pn2/5N1P/5PPK/3R1B2 w - - 3 30',
       '5rk1/PQp1qppp/3p4/1P2p3/R3Pn2/5N1P/5PPK/3R1B2 b - - 0 30'],
      dtype=object)

In [27]:
print(np.shape(Outcome))

(2843,)


In [28]:
#for index in input1:
#    print(index)

In [29]:
Outcome = df.values[:,1]
input1 = df.values[:,0]
input64 = []
input3 = []
for index in input1:
    
    print(index)
    if index.split('q ',1)[0] != index:
        index = index.split('q ',1)[0]
        index = index + 'q'
        
    elif index.split('Q ',1)[0] != index:
        index = index.split('Q ',1)[0]
        index = index + 'Q'
        
    elif index.split('Q ',1)[0] != index:
        index = index.split('Q ',1)[0]
        index = index + 'Q'
        
    elif index.split('w ',1)[0] != index:
        index = index.split('w ',1)[0]
        index = index + 'w'
        
    elif index.split('b ',1)[0] != index:
        index = index.split('b ',1)[0]
        index = index + 'b'
    index = index.split(" ",1)
    input64.append(index[0])
    input3.append(index[1])

    

rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq d3 0 1
rnbqkb1r/pppppppp/5n2/8/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 1 2
rnbqkb1r/pppppppp/5n2/6B1/3P4/8/PPP1PPPP/RN1QKBNR b KQkq - 2 2
rnbqkb1r/pppppp1p/5np1/6B1/3P4/8/PPP1PPPP/RN1QKBNR w KQkq - 0 3
rnbqkb1r/pppppp1p/5Bp1/8/3P4/8/PPP1PPPP/RN1QKBNR b KQkq - 0 3
rnbqkb1r/pppp1p1p/5pp1/8/3P4/8/PPP1PPPP/RN1QKBNR w KQkq - 0 4
rnbqkb1r/pppp1p1p/5pp1/8/3PP3/8/PPP2PPP/RN1QKBNR b KQkq e3 0 4
rnbqk2r/pppp1pbp/5pp1/8/3PP3/8/PPP2PPP/RN1QKBNR w KQkq - 1 5
rnbqk2r/pppp1pbp/5pp1/8/3PP3/5N2/PPP2PPP/RN1QKB1R b KQkq - 2 5
rnbqk2r/pppp1pbp/6p1/5p2/3PP3/5N2/PPP2PPP/RN1QKB1R w KQkq - 0 6
rnbqk2r/pppp1pbp/6p1/5P2/3P4/5N2/PPP2PPP/RN1QKB1R b KQkq - 0 6
rnbqk2r/pppp1pbp/8/5p2/3P4/5N2/PPP2PPP/RN1QKB1R w KQkq - 0 7
rnbqk2r/pppp1pbp/8/5p2/3P4/2P2N2/PP3PPP/RN1QKB1R b KQkq - 0 7
r1bqk2r/pppp1pbp/2n5/5p2/3P4/2P2N2/PP3PPP/RN1QKB1R w KQkq - 1 8
r1bqk2r/pppp1pbp/2n5/5p2/3P4/2PB1N2/PP3PPP/RN1QK2R b KQkq - 2 8
r1bqk2r/ppp2pbp/2n5/3p1p2/3P4/2PB1N2/PP3PPP/RN1QK2R w KQkq d6 0

IndexError: list index out of range

In [30]:
input64

['rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR',
 'rnbqkb1r/pppppppp/5n2/8/3P4/8/PPP1PPPP/RNBQKBNR',
 'rnbqkb1r/pppppppp/5n2/6B1/3P4/8/PPP1PPPP/RN1QKBNR',
 'rnbqkb1r/pppppp1p/5np1/6B1/3P4/8/PPP1PPPP/RN1QKBNR',
 'rnbqkb1r/pppppp1p/5Bp1/8/3P4/8/PPP1PPPP/RN1QKBNR',
 'rnbqkb1r/pppp1p1p/5pp1/8/3P4/8/PPP1PPPP/RN1QKBNR',
 'rnbqkb1r/pppp1p1p/5pp1/8/3PP3/8/PPP2PPP/RN1QKBNR',
 'rnbqk2r/pppp1pbp/5pp1/8/3PP3/8/PPP2PPP/RN1QKBNR',
 'rnbqk2r/pppp1pbp/5pp1/8/3PP3/5N2/PPP2PPP/RN1QKB1R',
 'rnbqk2r/pppp1pbp/6p1/5p2/3PP3/5N2/PPP2PPP/RN1QKB1R',
 'rnbqk2r/pppp1pbp/6p1/5P2/3P4/5N2/PPP2PPP/RN1QKB1R',
 'rnbqk2r/pppp1pbp/8/5p2/3P4/5N2/PPP2PPP/RN1QKB1R',
 'rnbqk2r/pppp1pbp/8/5p2/3P4/2P2N2/PP3PPP/RN1QKB1R',
 'r1bqk2r/pppp1pbp/2n5/5p2/3P4/2P2N2/PP3PPP/RN1QKB1R',
 'r1bqk2r/pppp1pbp/2n5/5p2/3P4/2PB1N2/PP3PPP/RN1QK2R',
 'r1bqk2r/ppp2pbp/2n5/3p1p2/3P4/2PB1N2/PP3PPP/RN1QK2R',
 'r1bqk2r/ppp2pbp/2n5/3p1p2/3P4/2PB1N2/PP3PPP/RN1Q1RK1',
 'r2qk2r/pppb1pbp/2n5/3p1p2/3P4/2PB1N2/PP3PPP/RN1Q1RK1',
 'r2qk2r/pppb1pbp/2n5/3p1p2/3P

In [31]:
print(type(input3))
input3

<class 'list'>


['b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b kq',
 'w kq',
 'b kq',
 'w kq',
 'b kq',
 'w kq',
 'b kq',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQ',
 'b KQ',
 'w KQ',
 'b KQ',
 'w KQ',
 'b KQ',
 'w KQ',
 'b KQ',
 'w KQ',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b',
 'w',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b KQkq',
 'w KQkq',
 'b kq',
 'w kq',
 'b kq',
 'w kq',
 'b kq',
 'w kq',
 'b kq',
 'w kq',
 'b kq',
 '

In [32]:
input2 = []
for char in input64:
    
    print(char)
    
    char = char.replace('1', '0_')
    char = char.replace('2', '0_0_')
    char = char.replace('3', '0_0_0_')
    char = char.replace('4', '0_0_0_0_')
    char = char.replace('5', '0_0_0_0_0_')
    char = char.replace('6', '0_0_0_0_0_0_')
    char = char.replace('7', '0_0_0_0_0_0_0_')
    char = char.replace('8', '0_0_0_0_0_0_0_0_')
    char = char.replace('p', '-1_')
    char = char.replace('n', '-3_')
    char = char.replace('b', '-3_')
    char = char.replace('r', '-5_')
    char = char.replace('q', '-9_')
    char = char.replace('k', '-10_')
    char = char.replace('P', '1_')
    char = char.replace('N', '3_')
    char = char.replace('B', '3_')
    char = char.replace('R', '5_')
    char = char.replace('Q', '9_')
    char = char.replace('K', '10_')
    char = char.replace('/','')
    char = char.split('_')
    del char[-1]
    print(char)
    input2.append(char)
    



rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR
['-5', '-3', '-3', '-9', '-10', '-3', '-3', '-5', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '1', '1', '1', '1', '5', '3', '3', '9', '10', '3', '3', '5']
rnbqkb1r/pppppppp/5n2/8/3P4/8/PPP1PPPP/RNBQKBNR
['-5', '-3', '-3', '-9', '-10', '-3', '0', '-5', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '0', '0', '0', '0', '0', '-3', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '1', '1', '1', '1', '5', '3', '3', '9', '10', '3', '3', '5']
rnbqkb1r/pppppppp/5n2/6B1/3P4/8/PPP1PPPP/RN1QKBNR
['-5', '-3', '-3', '-9', '-10', '-3', '0', '-5', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '0', '0', '0', '0', '0', '-3', '0', '0', '0', '0', '0', '0', '0', '0', '3', '0', 

In [33]:
names = ['square 1','square 2','square 3','square 4','square 5','square 6','square 7','square 8','square 9','square 10',
         'square 11','square 12','square 13','square 14','square 15','square 16','square 17','square 18','square 19','square 20',
         'square 21','square 22','square 23','square 24','square 25','square 26','square 27','square 28','square 29','square 30',
         'square 31','square 32','square 33','square 34','square 35','square 36','square 37','square 38','square 39','square 40',
         'square 41','square 42','square 43','square 44','square 45','square 46','square 47','square 48','square 49','square 50',
         'square 51','square 52','square 53','square 54','square 55','square 56','square 57','square 58','square 59','square 60',
         'square 61','square 62','square 63','square 64']


In [34]:
input2.insert(0, names)

In [35]:
with open('64_squares.csv', 'w', newline='', encoding='utf-8') as file_object:
    writer_object = csv.writer(file_object)
    for row in input2:
        print(row)
        writer_object.writerow(row)

['square 1', 'square 2', 'square 3', 'square 4', 'square 5', 'square 6', 'square 7', 'square 8', 'square 9', 'square 10', 'square 11', 'square 12', 'square 13', 'square 14', 'square 15', 'square 16', 'square 17', 'square 18', 'square 19', 'square 20', 'square 21', 'square 22', 'square 23', 'square 24', 'square 25', 'square 26', 'square 27', 'square 28', 'square 29', 'square 30', 'square 31', 'square 32', 'square 33', 'square 34', 'square 35', 'square 36', 'square 37', 'square 38', 'square 39', 'square 40', 'square 41', 'square 42', 'square 43', 'square 44', 'square 45', 'square 46', 'square 47', 'square 48', 'square 49', 'square 50', 'square 51', 'square 52', 'square 53', 'square 54', 'square 55', 'square 56', 'square 57', 'square 58', 'square 59', 'square 60', 'square 61', 'square 62', 'square 63', 'square 64']
['-5', '-3', '-3', '-9', '-10', '-3', '-3', '-5', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'

In [36]:
df2 = pd.read_csv("64_squares.csv")
df2.head()

square 1  square 2  square 3  square 4  square 5  square 6  square 7  \
0        -5        -3        -3        -9       -10        -3        -3   
1        -5        -3        -3        -9       -10        -3         0   
2        -5        -3        -3        -9       -10        -3         0   
3        -5        -3        -3        -9       -10        -3         0   
4        -5        -3        -3        -9       -10        -3         0   

   square 8  square 9  square 10  ...  square 55  square 56  square 57  \
0        -5        -1         -1  ...          1          1          5   
1        -5        -1         -1  ...          1          1          5   
2        -5        -1         -1  ...          1          1          5   
3        -5        -1         -1  ...          1          1          5   
4        -5        -1         -1  ...          1          1          5   

   square 58  square 59  square 60  square 61  square 62  square 63  square 64  
0          3          3          9         10          3          3          5  
1          3          3          9         10          3          3          5  
2          3          0          9         10          3          3          5  
3          3          0          9         10          3          3          5  
4          3          0          9         10          3          3          5  

[5 rows x 64 columns]

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [38]:
Outcome
input64 = df2.values[:,0:63]

In [39]:
print(np.shape(Outcome))
Outcome = np.delete(Outcome,(2018,2019,2020,2021))
for i in range(0, 82):
    Outcome = np.delete(Outcome,(2018,2019,2020,2021,2022,2023,2024,2025,2026,2027))
    
print(np.shape(Outcome))
Outcome = Outcome.reshape(2019,1)
print(np.shape(Outcome))
print(np.shape(input64))

(2843,)
(2019,)
(2019, 1)
(2019, 63)


In [40]:
print(np.shape(Outcome))
print(np.shape(input64))

Outcome = Outcome.astype(np.float)

(2019, 1)
(2019, 63)


C:\Users\ikego\AppData\Local\Temp\ipykernel_12252\3346810065.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Outcome = Outcome.astype(np.float)


In [41]:
print(Outcome)
print(input64)

[[  0.12]
 [  0.2 ]
 [  0.1 ]
 ...
 [ -8.25]
 [-49.85]
 [ 18.97]]
[[-5 -3 -3 ... 10  3  3]
 [-5 -3 -3 ... 10  3  3]
 [-5 -3 -3 ... 10  3  3]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [42]:
chess_data = np.hstack((input64, Outcome))
print(chess_data)

[[ -5.    -3.    -3.   ...   3.     3.     0.12]
 [ -5.    -3.    -3.   ...   3.     3.     0.2 ]
 [ -5.    -3.    -3.   ...   3.     3.     0.1 ]
 ...
 [  0.     0.     0.   ...   0.     0.    -8.25]
 [  0.     0.     0.   ...   0.     0.   -49.85]
 [  0.     0.     0.   ...   0.     0.    18.97]]


In [44]:
np.savetxt('chess_data.csv', chess_data, delimiter=',')

In [47]:
chess_data = np.loadtxt('chess_data.csv', delimiter=',')
chess_data

array([[ -5.  ,  -3.  ,  -3.  , ...,   3.  ,   3.  ,   0.12],
       [ -5.  ,  -3.  ,  -3.  , ...,   3.  ,   3.  ,   0.2 ],
       [ -5.  ,  -3.  ,  -3.  , ...,   3.  ,   3.  ,   0.1 ],
       ...,
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,  -8.25],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  , -49.85],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,  18.97]])

In [168]:
#Splitting the Data Training and Testing Sets
from sklearn.model_selection import train_test_split

# We specify this so that the train and test data set always have the same rows, respectively
np.random.seed(0)
input64_train, input64_test, Outcome_train, Outcome_test = train_test_split(input64, Outcome, train_size = 0.8, test_size = 0.2)

In [169]:
from sklearn import linear_model
print(np.shape(input64_test))
print(np.shape(Outcome_train))
print(type(input64_test))
print(type(Outcome_train))

(404, 63)
(1615, 1)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [176]:
reg = linear_model.LinearRegression()
reg.fit(input64_train, Outcome_train)
reg.score(input64_train, Outcome_train)

0.4363841665659143

In [177]:
reg.score(input64_test, Outcome_test)

0.3886771613662866

In [179]:
with open('64_squares_output.csv', 'w', newline='', encoding='utf-8') as file_object:
    writer_object = csv.writer(file_object)
    for row in Outcome:
        print(row)
        writer_object.writerow(row)

0.12


Error: iterable expected, not float